### PR TITLE
Create some abstractions to simplify interaction with Roam nodes.

### PR DESCRIPTION
**Pull request by Stvad**
General idea is to provide interface for Roam nodes that abstracts away complexities of interacting with it right now.

Current implementation does autosave on set. I'm not 100% sure about it. Let me know your thoughts. 

Also added the selection part, but haven't played with it much yet.

### CODE REVIEW

**Comment by panpiotrs** [comment]
That naming is quite confusing to me. What I would consider as RoamNode is this entire part of their html:
```
<div class="flex-h-box flex-align-start flex-justify-start">
    <div class="controls"><span class="block-expand opacity-none"><span class="bp3-icon-standard bp3-icon-caret-down rm-caret"></span></span><span class="simple-bullet-outer cursor-pointer" draggable="true"><span class="simple-bullet-inner"></span></span>
    </div>
    <div id="block-input-xxx-body-outline-xxx" class="roam-block dont-unfocus-block hoverparent rm-block-text" tabindex="0"><span>Block content</span></div>
    <div style="flex: 1 0 0px;"></div>
</div>
```

And generally I feel that it's too soon, we don't have enough use cases covered yet to abstract it that much, it's not hard at all to just get value of textarea for these 3 features and we can quickly refactor them later. I would wait to see what else can we do here, experiment more, play with things that require more than working with textarea values and selections and then find some common patterns.

`Roam.pressEnter()`, `Roam.getActiveRoamElement()`, `getInputEvent()` is what I would like to use, yes.

**Comment by Stvad** [comment]
👍 for getActiveRoamElement -> getRoamBlockInput.

I don't feel like having abstraction prevents us from experimenting further/playing/etc. As long as you don't force yourself into it. You can take useful parts from it and see how it breaks/ is insufficient and would have better idea on how improve it later?

**Comment by panpiotrs** [comment]
Let's see where it will lead.
About selections: both `element.selectionStart` and `element.selectionEnd` are required, we can keep them together as `Selection {start: number, end: number}`. When both are the same it means there is cursor at this position and nothing is selected.
I found out today that there is a function `element.setSelectionRange(start, end)` that can be used to update them https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange

**Comment by Stvad** [comment]
Ok, merging this now, will  look into adding the selection back properly in a bit. (feel freed to do so as well :)

**Comment by dalmo3** [comment]
@Stvad any reason why RoamNode's properties are readonly?

**Comment by Stvad** [comment]
Discouraging mutation tends to lead to code that is easier to reason about https://en.m.wikipedia.org/wiki/Immutable_object

**Pull request merged**
