### PR TITLE
Fix binding of shift+a in Vim Mode

### PR DESCRIPTION
**Pull request by d4hines**
Completed untested fix for #197 . I'll see if it builds here in a sec and if it does, I'll test it.

### CODE REVIEW

**Comment by d4hines** [comment]
Yup! Seems to work.

**Comment by Stvad** [comment]
thanks for the cotribution!

**Comment by Stvad** [comment]
will release a new version to the extension stores in a bit 🙂

**Comment by d4hines** [comment]
Can I haz release :smile:

**Comment by Stvad** [comment]
whoops, apologies, got bogged down by a bunch of things 😅. will publish
later tonight (and it should process in the next ~day)

**Comment by Stvad** [comment]
created a submission

**Comment by d4hines** [comment]
Cool! Thank you. And, of course, this is free software, so no worries!

**Pull request merged**
