### PR TITLE
Spatial Graph Mode

### PR DESCRIPTION
**Pull request by tntmarket**
##  Demo

Spatial Mode

### Save and restore previously created mind maps!

Save and Restore Workspaces

Copy the saved state using `Ctrl+Shift+s`, and paste it into a page. Then press `Ctrl+Shift+o` while on the page to restore the layout.

### Keyboard Shortcuts (Works with Vim!):

* `Ctrl + h/j/k/l` to jump between panels
* `Ctrl + Shift + h/j/k/l` to drag panels
* `Ctrl + =/-` to zoom

Jumping Between Panels

Pan/zoom with keyboard, will automatically select the vim panel in the middle of the screen.

### Select multiple nodes with `shift+click`:

Multiselect Demo

I got it to work with a custom theme, but I had to remove css selectors that ended with `[style*=".."]`, otherwise it lags with more than 5 pages.

## Implementation Overview

Cytoscape is rendered in the background. Roam is click-throughable, in order to interact with cytoscape, but Roam Panels themselves are clickable.

Sidebar pages are diffed between opens/closes, to track when nodes should be added/removed.

The last interacted with panel is tracked, to determine which edges to draw.

### Organization structure:

* `graph-visualization` => manages node/edge state
* `spatial-container` => sets up extra dom containers and styles
* `spatial-viewport` => manages the camera and selections
* `spatial-dom-synchronizer` => updates dom panels to match the graph visualization
* `roam-panel` => "panels" are now shared between vim mode and spatial mode
* `roam-panel-origin` => keeps track of which panel opened another panels, to draw edges

## Wishlist

* Opening a page should draw an edge (without having forward/back navigating draw edges)
* Manually resize panels (this seems non-trivial)
* Be able to "full screen" a panel temporarily

### CODE REVIEW

**Comment by Stvad** [comment]
Why not inject css in the code? :)

**Comment by Stvad** [comment]
Also I got weird results when Leyendecker theme was enabled. may want to add to instructions to disable custom themes?

**Comment by Stvad** [comment]
Want to be able to dynamically resize cards (and maybe shortcuts for "make larger/smaller")

**Comment by Stvad** [comment]
Also totally breaks intuitions for vim navigation between panels (where is next? where is down?). probably would want some id and a way to "move to panel x"

**Comment by Stvad** [comment]
vim navigation up/down does not scroll panels =\

**Comment by Stvad** [comment]
UX: I'd preserve scrolling up/down/left/right and would do zooming with some modifier pressed + scrolling

**Comment by Stvad** [comment]
Surfingkeys help with between panel navigation.   
Another wish: a shortcut to center the active panel (and/or a mode when focus follows panel switch)

**Comment by tntmarket** [comment]
> Also totally breaks intuitions for vim navigation between panels (where is next? where is down?). probably would want some id and a way to "move to panel x"

Long term, I'd like to support navigating left/right/up/down (with elementAtPos possibly).

Or maybe a "cycle through edges" shortcut

**Comment by tntmarket** [comment]
> Why not inject css in the code? :) 

I'll do that once I finalize it, it was easier to play with the css in Stylus during development

**Comment by tntmarket** [comment]
> vim navigation up/down does not scroll panels =\

Yeah, https://github.com/roam-unofficial/roam-toolkit/pull/160 fixes scrolling. I'll resume it at some point

**Comment by tntmarket** [comment]
> UX: I'd preserve scrolling up/down/left/right and would do zooming with some modifier pressed + scrolling

This might be non-trivial, I didn't find anything in Cytoscape's API to change the default controls :(

**Comment by Stvad** [comment]
* if you toggle it on and off - css changes linger - need to reload page to get rid of them
* min/max width/height should be configurable

**Comment by Stvad** [comment]
In latest revision scrolling does not work at all :(

**Comment by tntmarket** [comment]
> In latest revision scrolling does not work at all :(

Are you using a CSS theme? My scrolling works without a CSS theme, in both spatial/normal mode

**Comment by tntmarket** [comment]
Ok @Stvad , I think this is somewhat ready to review now. Unfortunately, these features seem pretty non-trivial:

* resize width/height
* use scroll wheel for pan

So I'm going to de-scope them from v1.

One problem I'm still trying to figure out is: how to make navigating forward/back in history draw edges, but have regular page opens draw edges. I currently make both not draw edges, by not clearing the "just interacted panel" whenever the url changes.

**Comment by Stvad** [comment]
oh, wow it grew to be quite large. will try to look this week. please poke me if I don't seem to be getting to it 😅

**Comment by Stvad** [comment]
still looks weird with Leyendecker theme =\ 
image

it seems it adds a background to panel or something like that, that the graph style does not override?

**Comment by Stvad** [comment]
Ctrl + arrow key conflicts with Mac global shortcuts (next/prev desktop, show all apps)

**Comment by tntmarket** [comment]
Yikes, latest Roam update broke a lot of things... I'll fix it up in the next week or so

**Comment by tntmarket** [comment]
> Ctrl + arrow key conflicts with Mac global shortcuts (next/prev desktop, show all apps)

Does `Ctrl + Shift + arrow` work? (I forgot the default shortcuts)

**Comment by tntmarket** [comment]
> Yikes, latest Roam update broke a lot of things... I'll fix it up in the next week or so

Ok, the issues have been fixed as far as I can tell.

Also, the lockfile changed to version 2 for some reason. The actual diff is still ~1.3k lines though. I tried to break it up into files that can be reviewed ~200 at a time.

**Comment by Stvad** [comment]
> > Ctrl + arrow key conflicts with Mac global shortcuts (next/prev desktop, show all apps)
> 
> Does `Ctrl + Shift + arrow` work? (I forgot the default shortcuts)

Up/down are already taken by other toolkit shortcuts. Left/right should work

**Comment by Stvad** [comment]
In the new version going between insert and normal mode causes the view to blink/re-render :(

**Comment by tntmarket** [comment]
> In the new version going between insert and normal mode causes the view to blink/re-render :(
> Also it seems it causes the switch to insert mode to fail, when it's initiated by mouse?

Yeah I get the blinking too. I currently re-render when editing blocks, in order to dynamically resize the panel as blocks are added/removed. One idea is to re-render when the difference is large enough, to avoid annoying flickers on microscopic changes. I'll try it out.

Entering insert mode with mouse is currently working for me.

**Comment by tntmarket** [comment]
> > > Ctrl + arrow key conflicts with Mac global shortcuts (next/prev desktop, show all apps)
> > 
> > 
> > Does `Ctrl + Shift + arrow` work? (I forgot the default shortcuts)
> 
> Up/down are already taken by other toolkit shortcuts. Left/right should work

I used `Ctrl + Command + Arrow`

**Comment by tntmarket** [comment]
Ok @Stvad, I'm confident enough to merge it into master now.

It actually doesn't work in Firefox due to https://github.com/cytoscape/cytoscape.js-cola/issues/51, but that seems non-trivial to fix, so I put a warning in the options UI.

Other than:
* some refactoring of the `roam-event`
* making vim mode use each sidebar page as an individual panel if graph mode is on

everything else is isolated from existing features. So I think there's a low chance this will break functionality for existing users.

I did some regression testing for vim + no spatial mode, and didn't find any issues.

**Comment by Stvad** [comment]
🔥

**Pull request merged**
